Buildling_a_Blog_Application/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls',namespace='blog')),
]+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

blog/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='blog'

urlpatterns = [
    path('',views.post_list,name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>',views.post_detail,name='post_detail'),
    path('<int:post_id>/share/',views.post_share,name='post_share'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset() \
            .filter(status='published')


class Post(models.Model):
    STATUS_CHOICES=(('draft','Draft'),('published','Published'))
    title=models.CharField(max_length=250)
    slug=models.SlugField(max_length=250,unique_for_date='publish')
    author=models.ForeignKey(User,on_delete=models.CASCADE,related_name='blog_posts')
    body=models.TextField()
    publish=models.DateTimeField(default=timezone.now)
    created=models.DateTimeField(auto_now_add=True)
    created=models.DateTimeField(auto_now=True)
    status=models.CharField(max_length=10,choices=STATUS_CHOICES,default='draft')

    objects=models.Manager()
    published=PublishedManager()


    class Meta:
        ordering=('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',args=[self.publish.year,self.publish.month,self.publish.day,self.slug])

    def get_absolute_url1(self):
        return reverse('blog:post_list')


class Comment(models.Model):
    post=models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    name=models.CharField(max_length=80)
    email=models.EmailField()
    body=models.TextField()
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    active=models.BooleanField(default=True)

    class Meta:
        ordering=('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name,self.post)

blog/forms.py
from django import forms
from .models import *

class EmailPostForm(forms.Form):
    name=forms.CharField(max_length=25)
    email=forms.EmailField()
    to=forms.EmailField()
    comments=forms.CharField(required=False,widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=('name','email','body')

blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import *
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from .forms import EmailPostForm,CommentForm
from django.core.mail import send_mail
# Create your views here.


def post_list(request):
    object_list=Post.published.all()
    paginator=Paginator(object_list,3)
    page=request.GET.get('page')
    try:
        posts=paginator.page(page)
    except PageNotAnInteger:
        posts=paginator.page(1)
    except EmptyPage:
        posts=paginator.page(paginator.num_pages)
    return render(request,'blog/post/list.html',{'page':page,'posts':posts})


def post_detail(request,year,month,day,post=None):
    post=get_object_or_404(Post,slug=post,status='published',publish__year=year,publish__month=month,publish__day=day)
    comments=post.comments.filter(active=True)
    new_comment=None
    if request.method=='POST':
        comment_form=CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment=comment_form.save(commit=False)
            new_comment.post=post
            new_comment.save()
    else:
        comment_form=CommentForm()
    return render(request,'blog/post/detail.html',{'post':post,'comments':comments,'new_comment':new_comment,'comment_form':comment_form})

def post_share(request,post_id):
    post=get_object_or_404(Post,id=post_id,status='published')
    sent=False
    if request.method=='POST':
        form=EmailPostForm(request.POST)
        if form.is_valid():
            cd=form.cleaned_data
            post_url=request.build_absolute_uri(post.get_absolute_url())
            subject='{} ({}) recommends you reading "{}"'.format(cd['name'],cd['email'],post.title)
            message='Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title,post_url,cd['name'],cd['comments'])
            send_mail(subject,message,'krushnam321@gmail.com',[cd['to']])
            sent=True
    else:
        form=EmailPostForm()
    return render(request,'blog/post/share.html',{'post':post,'form':form,'sent':sent})

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'bootstrap-4.4.1/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="{% static 'bootstrap-4.4.1/dist/js/bootstrap.min.js'%}"></script>
</head>
<body>
<div class="container bg-light" >
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{%block title %}{{post.title}}{% endblock %}

{% block content %}
<h1 class="text-info"> {{post.title}}</h1>
<p class="text-secondary">
    Published {{post.publish}} by {{post.author}}
</p>
<h1 class="text-primary">{{post.body|linebreaks}}</h1>
<p>
    <a href="{% url 'blog:post_share' post.id %}">Share this post</a>
</p>
{% with comments.count as total_comments %}
   <h2>
       {{ total_comments }} comment {{total_comments|pluralize}}
   </h2>
{% endwith %}
{% for comment in comments %}
  <div class="comment">
      <p class="info">
          Comment {{ forloop.counter }} by {{ comment.name }}
          {{ comment.created }}
      </p>
      {{ comment.body|linebreaks }}
  </div>
  {% empty %}
 <p>There are no comments yet.</p>
{% endfor %}
{% if new_comment %}
<h2>Your comment has been added.</h2>
{% else %}
<h2> Add a new comment</h2>
<form action="{{post.slug}}" method="post">
    <div class="form-group row">
    <label for="" class="col-sm-2 col-form-label">Name</label>
        <div class="col-sm-10">
            {{comment_form.name}}
        </div>
    </div>
    <div class="form-group row">
    <label for="" class="col-sm-2 col-form-label">Email</label>
        <div class="col-sm-10">
            {{comment_form.email}}
        </div>
    </div>
    <div class="form-group row">
    <label for="" class="col-sm-2 col-form-label">Comment</label>
        <div class="col-sm-10">
            {{comment_form.body}}
        </div>
    </div>
    {% csrf_token %}
    <button type="submit" class="btn btn-success">New Comment</button>
</form>
{% endif %}
{% endblock %}

blog/templates/blog/post/list.html
{% extends "blog/base.html"%}

{% block title %}My Blog{% endblock %}

{% block content %}
<h1>My Blog</h1>
{% for post in posts %}
<h3>
    <a href="{{post.get_absolute_url}} ">{{post.title}}</a>
</h3>
<p class="text-secondary"> Published {{post.publish}} by {{post.author}}</p>
<h1>{{ post.body|truncatewords:30|linebreaks }}</h1>
<p>
    <a href="{% url 'blog:post_share' post.id %}">Share this post</a>
</p>
{% endfor %}

{% include "pagination.html" with page=posts %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block title %}Share a post {% endblock %}

{% block content %}
{% if sent %}
  <h1>E-mail successfully sent</h1>
  <div class="alert alert-success">
    "{{post.title}}" was successfully sent to {{form.cleaned_data.to }}.
  </div>
{% else %}
<div class="jumbotron"><h1>Share "{{post.title}}" by e-mail</h1></div>
<form action="." method="post">
  <div class="form-group row">
    <label for="staticEmail" class="col-sm-2 col-form-label">Name</label>
    <div class="col-sm-10">
      {{form.name}}
    </div>
  </div>
  <div class="form-group row">
    <label for="" class="col-sm-2 col-form-label">Email</label>
    <div class="col-sm-10">
      {{form.email}}
    </div>
  </div>
  <div class="form-group row">
    <label for="" class="col-sm-2 col-form-label">To</label>
    <div class="col-sm-10">
      {{form.to}}
    </div>
  </div>
  <div class="form-group row">
    <label for="" class="col-sm-2 col-form-label">Comments</label>
    <div class="col-sm-10">
      {{form.comments}}
    </div>
  </div>
  {% csrf_token %}
  <button type="submit" class="btn btn-success" >Send e-mail</button>
</form>
{% endif %}
{% endblock %}

blog/templates/pagination.html
<div class="pagination">
  <span class="step-link">
    {% if page.has_previous %}
    <a href="?page={{page.previous_page_number}}">Previous</a>
    {% endif %}
    <span class="current">
      Page {{page.number}} of {{page.paginator.num_pages}}.
    </span>
    {% if page.has_next %}
      <a href="?page={{ page.next_page_number}}">Next</a>
    {% endif %}
  </span>
</div>